name: Lint Python code with ruff
on: [push, pull_request]

jobs:
  lint:
    name: Lint Python code with ruff
    runs-on: ubuntu-latest
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v3
      - run: pip install --user ruff
      - run: python -m ruff check .