name: Lint Python code with ruff

on: [push, pull_request]

jobs:
  lint:
    name: Lint Python code with ruff
    runs-on: ubuntu-latest
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          pipx install poetry
          poetry --version
          poetry env info
      - name: Install libraries with dev group
        run: |
          poetry install --with dev
      - name: Run ruff
        run: poetry run ruff check .