name: NetExec Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Building NetExec Binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        #os: [ubuntu-latest, macOS-latest, windows-latest]
        #python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: NetExec set up python on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Native Binary
      #if: runner.os == 'windows'
      run: |
        pip install pyinstaller
        pip install .
        pyinstaller netexec.spec
    - name: Upload Windows Binary
      if: runner.os == 'windows'
      uses: actions/upload-artifact@v3
      with:
        name: nxc.exe
        path: dist/nxc.exe
    - name: Upload Nix/OSx Binary
      if: runner.os != 'windows'
      uses: actions/upload-artifact@v3
      with:
        name: nxc-${{ matrix.os }}-${{ matrix.python-version }}
        path: bin/nxc
