name: NetExec Tests

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: Test for Py${{ matrix.python-version }}
    if: github.event.review.state == 'APPROVED'
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: NetExec set up python on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Install poetry
        run: |
          pipx install poetry --python python${{ matrix.python-version }}
          poetry --version
          poetry env info
      - name: Install libraries with dev group
        run: |
          poetry install --with dev
      - name: Run NetExec tests
        run: |
          netexec winrm 127.0.0.1
          netexec vnc 127.0.0.1
          netexec smb 127.0.0.1
          netexec ldap 127.0.0.1
          netexec wmi 127.0.0.1
          netexec rdp 127.0.0.1
          netexec mssql 127.0.0.1
          netexec ssh 127.0.0.1
          netexec ftp 127.0.0.1
          netexec smb 127.0.0.1 -M veeam